name: qr_pay
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.2
  barcode_scan: ^0.0.7
  share: ^0.5.3
  flutter_masked_text: ^0.6.0
  flutter_swiper : ^1.0.6
  firebase_core: ^0.2.5
  cloud_firestore: ^0.8.0
  http: 0.11.3+17
  fluttertoast: 2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - icon_mc.png
    - icon_visa.png
    - bagger.png
    - assets/anim/out0000.png
    - assets/anim/out0001.png
    - assets/anim/out0002.png
    - assets/anim/out0003.png
    - assets/anim/out0004.png
    - assets/anim/out0005.png
    - assets/anim/out0006.png
    - assets/anim/out0007.png
    - assets/anim/out0008.png
    - assets/anim/out0009.png
    - assets/anim/out00010.png
    - assets/anim/out00011.png
    - assets/anim/out00012.png
    - assets/anim/out00013.png
    - assets/anim/out00014.png
    - assets/anim/out00015.png
    - assets/anim/out00016.png
    - assets/anim/out00017.png
    - assets/anim/out00018.png
    - assets/anim/out00019.png
    - assets/anim/out00020.png
    - assets/anim/out00021.png
    - assets/anim/out00022.png
    - assets/anim/out00023.png
    - assets/anim/out00024.png
    - assets/anim/out00025.png
    - assets/anim/out00026.png
    - assets/anim/out00027.png
    - assets/anim/out00028.png
    - assets/anim/out00029.png
    - assets/anim/out00030.png
    - assets/anim/out00040.png
    - assets/anim/out00041.png
    - assets/anim/out00042.png
    - assets/anim/out00043.png
    - assets/anim/out00044.png
    - assets/anim/out00045.png
    - assets/anim/out00046.png
    - assets/anim/out00047.png
    - assets/anim/out00048.png
    - assets/anim/out00049.png
    - assets/anim/out00050.png
    - assets/anim/out00051.png
    - assets/anim/out00052.png
    - assets/anim/out00053.png
    - assets/anim/out00054.png
    - assets/anim/out00055.png
    - assets/anim/out00056.png
    - assets/anim/out00057.png
    - assets/anim/out00058.png
    - assets/anim/out00059.png
    - assets/anim/out00060.png
    - assets/anim/out00061.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
